package com.cs2c.project.module.webservice;

import com.cs2c.project.module.webservice.domain.DiskInformation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-07-01T15:42:39.416+08:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://service.webservice.module.project.cs2c.com/", name = "webServiceInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface WebServiceInterface {

    @WebMethod
    @RequestWrapper(localName = "getMemInfo", targetNamespace = "http://service.webservice.module.project.cs2c.com/", className = "com.cs2c.webservice.client.GetMemInfo")
    @ResponseWrapper(localName = "getMemInfoResponse", targetNamespace = "http://service.webservice.module.project.cs2c.com/", className = "com.cs2c.webservice.client.GetMemInfoResponse")
    @WebResult(name = "getMemInfo", targetNamespace = "")
    public WebServiceResponse getMemInfo(

        @WebParam(name = "startTime", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar startTime,
        @WebParam(name = "endTime", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar endTime,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password
    );

    @WebMethod
    @RequestWrapper(localName = "getNetFlewInfo", targetNamespace = "http://service.webservice.module.project.cs2c.com/", className = "com.cs2c.webservice.client.GetNetFlewInfo")
    @ResponseWrapper(localName = "getNetFlewInfoResponse", targetNamespace = "http://service.webservice.module.project.cs2c.com/", className = "com.cs2c.webservice.client.GetNetFlewInfoResponse")
    @WebResult(name = "getNetFlewInfo", targetNamespace = "")
    public WebServiceResponse getNetFlewInfo(

        @WebParam(name = "startTime", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar startTime,
        @WebParam(name = "endTime", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar endTime,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password
    );

    @WebMethod
    @RequestWrapper(localName = "getCpuInfo", targetNamespace = "http://service.webservice.module.project.cs2c.com/", className = "com.cs2c.webservice.client.GetCpuInfo")
    @ResponseWrapper(localName = "getCpuInfoResponse", targetNamespace = "http://service.webservice.module.project.cs2c.com/", className = "com.cs2c.webservice.client.GetCpuInfoResponse")
    @WebResult(name = "getCpuInfo", targetNamespace = "")
    public WebServiceResponse getCpuInfo(

        @WebParam(name = "startTime", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar startTime,
        @WebParam(name = "endTime", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar endTime,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password
    );

    @WebMethod
    @RequestWrapper(localName = "getSysRequestInfo", targetNamespace = "http://service.webservice.module.project.cs2c.com/", className = "com.cs2c.webservice.client.GetSysRequestInfo")
    @ResponseWrapper(localName = "getSysRequestInfoResponse", targetNamespace = "http://service.webservice.module.project.cs2c.com/", className = "com.cs2c.webservice.client.GetSysRequestInfoResponse")
    @WebResult(name = "getSysRequestInfo", targetNamespace = "")
    public WebServiceResponse getSysRequestInfo(

        @WebParam(name = "startTime", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar startTime,
        @WebParam(name = "endTime", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar endTime,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password
    );

    @WebMethod
    @RequestWrapper(localName = "getFileTransferInfo", targetNamespace = "http://service.webservice.module.project.cs2c.com/", className = "com.cs2c.webservice.client.GetFileTransferInfo")
    @ResponseWrapper(localName = "getFileTransferInfoResponse", targetNamespace = "http://service.webservice.module.project.cs2c.com/", className = "com.cs2c.webservice.client.GetFileTransferInfoResponse")
    @WebResult(name = "getFileTransferInfo", targetNamespace = "")
    public WebServiceResponse getFileTransferInfo(

        @WebParam(name = "startTime", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar startTime,
        @WebParam(name = "endTime", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar endTime,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password
    );

    @WebMethod
    @RequestWrapper(localName = "getDDOSInfo", targetNamespace = "http://service.webservice.module.project.cs2c.com/", className = "com.cs2c.webservice.client.GetDDOSInfo")
    @ResponseWrapper(localName = "getDDOSInfoResponse", targetNamespace = "http://service.webservice.module.project.cs2c.com/", className = "com.cs2c.webservice.client.GetDDOSInfoResponse")
    @WebResult(name = "getDDOSInfo", targetNamespace = "")
    public WebServiceResponse getDDOSInfo(

        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password
    );

    @WebMethod
    @RequestWrapper(localName = "getDiskInfo", targetNamespace = "http://service.webservice.module.project.cs2c.com/", className = "com.cs2c.webservice.client.GetDiskInfo")
    @ResponseWrapper(localName = "getDiskInfoResponse", targetNamespace = "http://service.webservice.module.project.cs2c.com/", className = "com.cs2c.webservice.client.GetDiskInfoResponse")
    @WebResult(name = "getDiskInfo", targetNamespace = "")
    public WebServiceResponse getDiskInfo(

        @WebParam(name = "diskInformation", targetNamespace = "")
                DiskInformation diskInformation,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password
    );
}
