package com.cs2c.project.module.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-07-01T15:42:39.468+08:00
 * Generated source version: 3.3.6
 *
 */
@WebServiceClient(name = "WebServiceInterfaceImplService",
                  wsdlLocation = "http://192.168.10.129:8001/ws?wsdl",
                  targetNamespace = "http://service.webservice.module.project.cs2c.com")
public class WebServiceInterfaceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.webservice.module.project.cs2c.com", "WebServiceInterfaceImplService");
    public final static QName WebServiceInterfacePort = new QName("http://service.webservice.module.project.cs2c.com", "webServiceInterfacePort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.10.129:8001/ws?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WebServiceInterfaceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://192.168.10.129:8001/ws?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WebServiceInterfaceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WebServiceInterfaceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceInterfaceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public WebServiceInterfaceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WebServiceInterfaceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WebServiceInterfaceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns WebServiceInterface
     */
    @WebEndpoint(name = "webServiceInterfacePort")
    public WebServiceInterface getWebServiceInterfacePort() {
        return super.getPort(WebServiceInterfacePort, WebServiceInterface.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceInterface
     */
    @WebEndpoint(name = "webServiceInterfacePort")
    public WebServiceInterface getWebServiceInterfacePort(WebServiceFeature... features) {
        return super.getPort(WebServiceInterfacePort, WebServiceInterface.class, features);
    }

}
